print("--calculo de desconto--")
valordoproduto = float(input("digite o valor do produto:"))
desconto = int(input("digite o valor do desconto:"))
valorfinal = (valordoproduto)*(1-(desconto/100))
print("valor final do produto e:", valorfinal)
