print("--calcular media ponderada--")
n1 = float(input("digite a primeira nota:"))
p1 = float(input("digite o peso da primeira nota:"))
n2 = float(input("digite a segunda nota:"))
p2 = float(input("digite o peso da segunda nota:"))
n3 = float(input("digite a terceira nota:"))
p3 = float(input("digite o peso da terceira nota:"))
media = ((n1*p1)+(n2*p2)+(n3*p3))/(p1+p2+p3)
print("a media das notas é:", media)